# Generated by Django 5.2.12 on 2026-10-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('from_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_out', to='fleet.office')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_in', to='fleet.office')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['vehicle', '-assigned_at'], name='fleet_vehic_vehicle_9de2eb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_office', models.F('to_office')), _negated=True), name='assignment_moves_between_different_offices')],
            },
        ),
    ]
